language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
git:
  depth: 5
  quiet: true
before_install:
  - rm -rf .git
  - npm set audit false
install:
  - cd ..
  - git clone https://github.com/theme-suka/hexo-theme-unit-test.git --depth=2
  - rm -rf hexo-theme-unit-test/.git
  - mkdir -p suka-theme-test
  - mv -f hexo-theme-unit-test/* suka-theme-test
  - cd suka-theme-test
  - npm i > /dev/null
  - chmod +x ./install-theme.sh
  - ./install-theme.sh
script:
  - chmod +x ./build.sh
  - ./build.sh
  - chmod +x ./deploy.sh
  - ./deploy.sh > /dev/null
cache:
  directories:
  - /home/travis/build/SukkaW/suka-theme-test/themes/suka/node_modules
  - /home/travis/build/SukkaW/suka-theme-test/node_modules
  timeout: 60
