language: node_js

sudo: required

node_js:
  - 9.7.1
cache:
  directories:
    - node_modules

branches:
  only:
    - yuque-hexo
# env:
#   global:
#     - YUQUE-TOKEN: KHWUXJKjkjiLYiVlvTRtRRQPLrX5M9U94eMTbyah
#     - DEBUG: common-bin

before_install:
  - npm install -g hexo-cli
  - cd themes/suka
  - npm install  --silent
  - cd ../..
  - git config user.name "YUUtan1994"
  - git config user.email "yuutan1994@163.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml

# Start: Build Lifecycle
install:
  - npm install --silent
  - npm install hexo-deployer-git --save

script:
  - npm run deploy

after_script:
# End: Build LifeCycle
